version: '3.3'
services:

    mongo:
        build:
            context: ./mongodb
            dockerfile: Dockerfile
        ports:
            - '27017:27017'
        volumes:
            - mongodb-data:/data/db

    my-movies:
        build:
            context: ./my-movies
            dockerfile: Dockerfile
        ports:
            - '3003:3003'
        depends_on:
            - mongo
        environment:
            - MONGO_URI=mongodb://mongo:27017/movies

    
    info:
        build:
            context: ./info
            dockerfile: Dockerfile
        ports:
            - '3004:3004'


    random:
        build:
            context: ./random
            dockerfile: Dockerfile
        ports:
            - '3002:3002'
        depends_on:
            - my-movies

volumes:
    mongodb-data:
