version: '3.3'
services:

    mongo:
        build:
            context: ./mongodb
            dockerfile: Dockerfile
        ports:
            - '27017:27017'
        volumes:
            - mongodb-data:/data/db

    my-movies:
        build:
            context: ./my-movies
            dockerfile: Dockerfile
        ports:
            - '3003:3003'
        links:
            - mongo
        environment:
            - MONGO_URI=mongodb://mongo:27017/movies

volumes:
    mongodb-data:
